[workspace]

members = [
    "service/domain/person",
    "service/service_common",
    "service/message_broker",
    "service/gateway",
    "libraries/common",
    "libraries/store",
    "libraries/message_client",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
serde = "1.0.147"
serde_json = "1.0.87"
bincode = "1.3.3"
tokio = "1.21.2"
uuid = "1.1.2"
mongodb = "2.3.1"
chrono = "0.4.22"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
axum = "0.5.17"
tower-http = "0.3.4"
futures-util = "0.3.25"
async-trait = "0.1.58"
dirs = "4.0.0"
tower = "0.4.13"
queue-file = "1.4.6"
reqwest = "0.11.12"
tokio-tungstenite = "0.17.2"
futures ="0.3.25"
axum-core ="0.2.9"
hyper = "0.14.20"
toml = "0.5.9"
serde_yaml = "0.9"
regex = "1.6.0" 
hyper-rustls = "0.23.0"
rustls = "0.20.7"
openidconnect = "2.4.0"
async-redis-session = "0.2.2"
async-session = "3.0.0"
axum-sessions = "0.3.1"
rand = "0.8.5"

[workspace.package]
version = "0.1.0"
authors = ["Nordine Bittich"]
description = "Simple ERP"
documentation = "https://github.com/nbittich/sequeda"
rust-version = "1.64.0"
edition = "2021"
license = "MPL-2.0"