pub const CORS_ALLOW_ORIGIN: &str = "CORS_ALLOW_ORIGIN";
pub const SERVICE_HOST: &str = "SERVICE_HOST";
pub const SERVICE_PORT: &str = "SERVICE_PORT";
pub const SERVICE_CONFIG_VOLUME: &str = "SERVICE_CONFIG_VOLUME";
pub const SERVICE_DATA_VOLUME: &str = "SERVICE_DATA_VOLUME";
pub const SERVICE_APPLICATION_NAME: &str = "SERVICE_APPLICATION_NAME";
pub const SERVICE_COLLECTION_NAME: &str = "SERVICE_COLLECTION_NAME";
