mod constants;
pub mod tenant;

pub use constants::{
    CORS_ALLOW_ORIGIN, SERVICE_APPLICATION_NAME, SERVICE_COLLECTION_NAME, SERVICE_CONFIG_VOLUME,
    SERVICE_DATA_VOLUME, SERVICE_HOST, SERVICE_PORT,
};
