routes:
  - id: yahoo_finance_chart
    uri: https://query1.finance.yahoo.com
    predicates:
    - !host api.somehost.org
    - !path /proxy/yahoo-finance/chart/**
    filters:
    - !rewrite_path
        source: /proxy/yahoo-finance/chart/(?P<segment>.*)
        dest: /v8/finance/chart/${segment}
    authorizations:
    - !authorization
        method: "GET"
        has_roles:
        - creep
  - id: person_find_all
    uri: http://person
    predicates:
    - !path /person/find-all/** # todo doesn't work with /find-all/ but works with /find-all
    authorizations:
    - !authorization
        method: "GET"
        has_roles:
        - creep
    filters:
    - !rewrite_path
        source: /person/(?P<segment>.*)
        dest: /${segment}
  - id: person_upsert
    uri: http://person
    filters:
    - !rewrite_path
        source: /person/(?P<segment>.*)
        dest: /${segment}
    predicates:
    - !path /person/
    - !method POST
    authorizations:
    - !authorization
        method: "POST"
        has_roles:
        - creep