routes:
  - id: yahoo_finance_chart
    uri: https://query1.finance.yahoo.com
    predicates:
      - !host api.somehost.org
      - !path /proxy/yahoo-finance/chart/**
    filters:
      - !rewrite_path
        source: /proxy/yahoo-finance/chart/(?P<segment>.*)
        dest: /v8/finance/chart/${segment}
      - !remove_request_header Cookie
    authorizations:
      - !authorization
        method: "GET"
        has_roles:
          - creep
          - demo
  - id: api
    uri: http://gateway
    predicates:
      - !path /api/**
    filters:
      - !rewrite_path
        source: /api/(?P<segment>.*)
        dest: /${segment}
# person
  - id: person_find_all
    uri: http://person
    predicates:
      - !path /person/find-all/**
    authorizations:
      - !authorization
        method: "GET"
        has_roles:
          - creep
          - demo
    filters:
      - !rewrite_path
        source: /person/find-all/**
        dest: /find-all

  - id: person_current
    uri: http://person
    predicates:
      - !path /person/current/**
    authorizations:
      - !authorization
        method: "GET"
        has_roles:
          - creep
          - demo
    filters:
      - !rewrite_path
        source: /person/current/**
        dest: /current
  - id: person_upsert
    uri: http://person
    filters:
      - !rewrite_path
        source: /person/**
        dest: /
    predicates:
      - !path /person/**
      - !method POST
    authorizations:
      - !authorization
        method: "POST"
        has_roles:
          - creep
          - demo
  # positions
  - id: position_find_one
    uri: http://org-position
    predicates:
      - !path /orgs/position/find-one/**
    authorizations:
      - !authorization
        method: "GET"
        has_roles:
          - creep
          - demo
    filters:
      - !rewrite_path
        source: /orgs/position/find-one/(?P<segment>.*)
        dest: /find-one/${segment}
  - id: position_find_all
    uri: http://org-position
    predicates:
      - !path /orgs/position/find-all/**
    authorizations:
      - !authorization
        method: "GET"
        has_roles:
          - creep
          - demo
    filters:
      - !rewrite_path
        source: /orgs/position/find-all/**
        dest: /find-all
  - id: position_upsert
    uri: http://org-position
    filters:
      - !rewrite_path
        source: /orgs/position/**
        dest: /
    predicates:
      - !path /orgs/position/**
      - !method POST
    authorizations:
      - !authorization
        method: "POST"
        has_roles:
          - creep
          - demo
  # members
  - id: members_find_all
    uri: http://org-members
    predicates:
      - !path /orgs/members/find-all/**
    authorizations:
      - !authorization
        method: "GET"
        has_roles:
          - creep
          - demo
    filters:
      - !rewrite_path
        source: /orgs/members/find-all/**
        dest: /find-all
  - id: members_find_by_org
    uri: http://org-members
    predicates:
      - !path /orgs/members/find-by-org/**
    authorizations:
      - !authorization
        method: "GET"
        has_roles:
          - creep
          - demo
    filters:
      - !rewrite_path
        source: /orgs/members/find-by-org/(?P<segment>.*)
        dest: /find-by-org/${segment}
  - id: member_upsert
    uri: http://org-members
    filters:
      - !rewrite_path
        source: /orgs/members/**
        dest: /
    predicates:
      - !path /orgs/members/**
      - !method POST
    authorizations:
      - !authorization
        method: "POST"
        has_roles:
          - creep
  # orgs
  - id: orgs_current
    uri: http://orgs
    predicates:
      - !path /orgs/current/**
    authorizations:
      - !authorization
        method: "GET"
        has_roles:
          - creep
          - demo
    filters:
      - !rewrite_path
        source: /orgs/current/**
        dest: /current
  - id: orgs_find_all
    uri: http://orgs
    predicates:
      - !path /orgs/find-all/**
    authorizations:
      - !authorization
        method: "GET"
        has_roles:
          - creep
          - demo
    filters:
      - !rewrite_path
        source: /orgs/find-all/**
        dest: /find-all
  - id: orgs_upsert
    uri: http://orgs
    filters:
      - !rewrite_path
        source: /orgs/**
        dest: /
    predicates:
      - !path /orgs/**
      - !method POST
    authorizations:
      - !authorization
        method: "POST"
        has_roles:
          - creep
          - demo
  # geo_entities
  - id: geo_entities
    uri: http://geo-entities
    filters:
      - !rewrite_path
        source: /geo/**
        dest: /
    predicates:
      - !path /geo/**
      - !method GET
  - id: upload_service
    uri: http://uploads
    filters:
      - !rewrite_path
        source: /uploads/(?P<segment>.*)
        dest: /${segment}
    predicates:
      - !path /uploads/**
    authorizations:
      - !authorization
        method: "POST"
        has_roles:
          - creep
          - demo
  - id: audit_log_find_all
    uri: http://auditlog
    predicates:
      - !path /audit-log/find-all/**
    authorizations:
      - !authorization
        method: "GET"
        has_roles:
          - creep
          - demo
    filters:
      - !rewrite_path
        source: /audit-log/find-all/**
        dest: /find-all
  # - id: keycloak
  #   uri: http://keycloak:80
  #   filters:
  #     - !add_request_header
  #       key: "X-Forwarded-Port"
  #       value: "443"
  #   predicates:
  #     - !host auth.somehost.org