order: 1
routes:
  - id: geo_entities
    uri: http://geo-entities
    filters:
      - !rewrite_path
        source: /geo/**
        dest: /
    predicates:
      - !path /geo/**
      - !method GET
  