order: 1
routes:
  - id: position_find_one
    uri: http://org-position
    predicates:
      - !path /orgs/position/find-one/**
    authorizations:
      - !authorization
        method: "GET"
        has_roles:
          - creep
          - demo
    filters:
      - !rewrite_path
        source: /orgs/position/find-one/(?P<segment>.*)
        dest: /find-one/${segment}
  - id: position_find_all
    uri: http://org-position
    predicates:
      - !path /orgs/position/find-all/**
    authorizations:
      - !authorization
        method: "GET"
        has_roles:
          - creep
          - demo
    filters:
      - !rewrite_path
        source: /orgs/position/find-all/**
        dest: /find-all
  - id: position_upsert
    uri: http://org-position
    filters:
      - !rewrite_path
        source: /orgs/position/**
        dest: /
    predicates:
      - !path /orgs/position/**
      - !method POST
    authorizations:
      - !authorization
        method: "POST"
        has_roles:
          - creep
          - demo
  