version: "3.9"
services:
  ####### MongoDB #######
  mongo:
    image: mongo
    networks:
      sequeda:
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data/db:/data/db
  ####### Keycloak #######
  keycloak-postgresql:
    restart: always
    networks:
      sequeda:
    image: "postgres"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    volumes:
      - ./data/keycloak_postgresql:/var/lib/postgresql/data
  keycloak:
    restart: always
    image: nbittich/keycloak:20.0.0
    networks:
      sequeda:
    environment:
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://keycloak-postgresql:5432/keycloak"
      KC_PROXY: edge
    command: start --optimized --http-port=80
    depends_on:
      - keycloak-postgresql

  ####### Redis #######
  redis:
    image: redis:alpine
    restart: always
    networks:
      sequeda:
    command: redis-server  --appendonly yes
    volumes:
      - ./data/redis:/data
  ####### Gateway #######
  gateway:
    build:
      context: ../
      args:
        CRATE_NAME: sequeda_gateway
    volumes:
      - ./config/gateway/config.yml:/config/gateway.yml
    environment:
      RUST_LOG: DEBUG
      SERVICE_CONFIG_VOLUME: /config
      SERVICE_HOST: 0.0.0.0
      SERVICE_PORT: 80
      OPENID_ENABLED: "true"
      APP_ROOT_URL: "https://api.somehost.org"
      OPENID_ISSUER_URL: "http://auth.somehost.org/realms/sequeda"
      OPENID_CLIENT_ID: "sequeda-auth"
      OPENID_CLIENT_SECRET: "X9quJGCCpBISQt6uNs62gkPeYd4g2gsp"
      SESSION_REDIS_URL: "redis://redis"
    restart: "always"
    networks:
      sequeda:
  ####### service person - for testing #######
  person:
    build:
      context: ../
      args:
        CRATE_NAME: sequeda_person
    environment:
      RUST_LOG: DEBUG
      SERVICE_CONFIG_VOLUME: /config
      SERVICE_HOST: 0.0.0.0
      SERVICE_PORT: 80
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_USERNAME: root
      MONGO_PASSWORD: root
      MONGO_ADMIN_DATABASE: admin
    restart: "always"
    networks:
      sequeda:
      
networks:
  sequeda: