version: "3.9"
services:
  gateway:
    environment:
      DEMO_ACCOUNT: "true" # todo this doesn't go to production
      OPENID_DISABLE_SSL_ISSUER: "true"

  mongo-express:
    image: mongo-express
    networks:
      sequeda:
    restart: "no"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    ports:
      - 8081:8081
  keycloak:
    environment:
      KC_HOSTNAME_URL: "https://auth.somehost.org"
      KC_HOSTNAME_ADMIN_URL: "https://auth.somehost.org"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: root
    user: root
    networks:
      sequeda:
    #command: start --optimized --http-port=80  --log-level=DEBUG
    volumes:
      - ./config/keycloak-dev/export:/tmp/export
      - ./config/keycloak-dev/import:/tmp/import
  mongo:
    ports:
      - 27019:27017
  redis:
    ports:
      - "6379:6379"
  tlsproxy:
    image: caddy:2
    networks:
      sequeda:
        aliases:
          - auth.somehost.org
    ports:
      - "443:443"
      - "80:80"
    environment:
      API_ADDRESS: "api.somehost.org"
      AUTH_ADDRESS: "auth.somehost.org"
    volumes:
      - ./config/tlsproxy-mock/Caddyfile:/etc/caddy/Caddyfile
